
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author VIRAJ
 */
public class bank_document extends javax.swing.JFrame {
    File f2,f1,f3;
    /**
     * Creates new form bank_document
     */
    public bank_document() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pass_photo = new javax.swing.JButton();
        pan_photo = new javax.swing.JButton();
        adhar_photo = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        adhar_upload = new javax.swing.JLabel();
        passport_upload = new javax.swing.JLabel();
        pan_upload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 191, 68));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Upload Documents :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("----- Passport Size Photo -----");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("---- Adhar Card Photo ----");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("---- Pan Card Photo ----");

        pass_photo.setBackground(new java.awt.Color(255, 153, 51));
        pass_photo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        pass_photo.setText("Select ");
        pass_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass_photoMouseClicked(evt);
            }
        });
        pass_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_photoActionPerformed(evt);
            }
        });

        pan_photo.setBackground(new java.awt.Color(255, 153, 51));
        pan_photo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        pan_photo.setText("Select ");
        pan_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pan_photoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pan_photoMouseEntered(evt);
            }
        });
        pan_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pan_photoActionPerformed(evt);
            }
        });

        adhar_photo.setBackground(new java.awt.Color(255, 153, 51));
        adhar_photo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        adhar_photo.setText("Select ");
        adhar_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adhar_photoMouseClicked(evt);
            }
        });
        adhar_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adhar_photoActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(204, 51, 0));
        Submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        adhar_upload.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N

        passport_upload.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N

        pan_upload.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(185, 185, 185)
                                            .addComponent(jLabel2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(8, 8, 8))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(adhar_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(68, 68, 68)))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pass_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adhar_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pan_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passport_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(pan_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_photo)
                    .addComponent(passport_upload))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adhar_photo)
                    .addComponent(adhar_upload))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pan_photo)
                    .addComponent(pan_upload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adhar_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adhar_photoActionPerformed
        // TODO add your handling code here:
         JFileChooser fc=new JFileChooser();    
        int i=fc.showOpenDialog(this);    
        if(i==JFileChooser.APPROVE_OPTION){    
            f2=fc.getSelectedFile();
         System.out.println(f2.getName());
        }
    }//GEN-LAST:event_adhar_photoActionPerformed

    private void pass_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_photoMouseClicked
        // TODO add your handling code here:
        
        new select_document().setVisible(true);
     this.dispose();
   
    }//GEN-LAST:event_pass_photoMouseClicked

    private void adhar_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adhar_photoMouseClicked
        // TODO add your handling code here:
          new select_document().setVisible(true);
     this.dispose();
      passport_upload.setText("");
    }//GEN-LAST:event_adhar_photoMouseClicked

    private void pan_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_photoMouseClicked
        // TODO add your handling code here:
           new select_document().setVisible(true);
     this.dispose();
      adhar_upload.setText("Photo Uploaded..!!");
    }//GEN-LAST:event_pan_photoMouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
           
     this.dispose();
    }//GEN-LAST:event_SubmitMouseClicked

    private void pan_photoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pan_photoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pan_photoMouseEntered

    private void pass_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_photoActionPerformed
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser();    
        int i=fc.showOpenDialog(this);    
        if(i==JFileChooser.APPROVE_OPTION){    
            f1=fc.getSelectedFile();
         System.out.println(f1.getName());}
        
        
        
    }//GEN-LAST:event_pass_photoActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
try
        
        {
               this.dispose();
               new thanks_page().setVisible(true);
            String url = "jdbc:mysql://localhost:3306/bank_system?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String uname =  "root";
            String pass = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url , uname , pass);   
            //System.out.println("Connection Established Successfull and the DATABASE NAME IS:"+ con.getMetaData().getURL());
           
        PreparedStatement stmt=con.prepareStatement("INSERT INTO `documents`(`Profile Photo`, `adhar_photo`, `pan_photo`) VALUES(?,?,?)");
        stmt.setString(1, f1.getName());
        stmt.setString(2, f2.getName());
        stmt.setString(3, f3.getName());
        //Inserting Blob type
       String photo=f1.getAbsolutePath();
       InputStream in1 = new FileInputStream(photo);
       String adhar_photo=f2.getAbsolutePath();
       InputStream in2 = new FileInputStream(adhar_photo);
       String pan_photo=f3.getAbsolutePath();
       InputStream in3 = new FileInputStream(pan_photo);
        stmt.setBlob(1,in1);
        stmt.setBlob(2,in2);
        stmt.setBlob(3,in3);
        stmt.execute();
            con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace(System.out);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void pan_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pan_photoActionPerformed
        // TODO add your handling code here:
         JFileChooser fc=new JFileChooser();    
        int i=fc.showOpenDialog(this);    
        if(i==JFileChooser.APPROVE_OPTION){    
            f3=fc.getSelectedFile();
        System.out.println(f3.getName());}
        
    }//GEN-LAST:event_pan_photoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bank_document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bank_document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bank_document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bank_document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bank_document().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton adhar_photo;
    private javax.swing.JLabel adhar_upload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pan_photo;
    private javax.swing.JLabel pan_upload;
    private javax.swing.JButton pass_photo;
    private javax.swing.JLabel passport_upload;
    // End of variables declaration//GEN-END:variables
}
